### ISSUE TITLE
Implement ?restart

### ISSUE THREAD

**Issue by rawsonj** [rawsonj/triviabot#10]

**Comment by rawsonj** [comment]
Oh, I remember what this is about.

It's a convenience function because when trivia's base code updates, it won't update the running program until it gets killed and restarted, so I wanted to just ?restart and cause it to die and such.

Considering the relative difficulty in implementing this, and likely the stdout, stderr and stdin file descriptor hoo-ha involved in trying to make this work effectively, I'm going to close this as don't implement.

Frankly, it's not that big of a deal to kill the bot and start it again.

**Comment by genius3000** [comment]
If interested yet, I did get a ?restart working in my fork. It seems to work in my testing at least.
The command sets '_restarting' True, quits and then the 'def connectionLost' handles it:
[https://github.com/genius3000/triviabot/blob/483023edf295476ef08c4e3b9206c06fe936d1e5/trivia.py#L557](url)
Ignore the comment above it yet, I must have forgotten to remove it.

I could re-work it to this current master branch and send a PR.

**Comment by rawsonj** [comment]
Hm, ok, reviewing how you did that I think it could actually work. Using execl in an exception handler would replace the current process with the new one, and in this case it would be the updated script.

I'll reopen this. If you want to submit a PR I'll review and merge it. If you're busy, the link you posted is enough to go off of for me to do something similar.

Thanks!
