### ISSUE TITLE
triviabot thinks the string 'trivial persuit' matches its name so looks at you funny.

### ISSUE THREAD

**Issue by rawsonj** [rawsonj/triviabot#25]
Fix command parsing.

**Comment by andy5995** [comment]
Is this fixed? I'm trying it but tb isn't looking at me funny.

**Comment by andy5995** [comment]
I tested it with questions that have triviasomething as an answer and had no problems.

**Comment by rawsonj** [comment]
In talking with Andy and trying to trigger this myself, I think this issue is in fact resolved.

Must have fixed it along the way at some point and forgot to close the issue.
