### ISSUE TITLE
show correct answer when someone wins

### ISSUE THREAD

**Issue by jasonaowen** [rawsonj/triviabot#27]
Some questions inspire guessing, and if someone guess several answers in quick succession, one of which is right, it's not obvious what the correct answer is.

**Comment by andy5995** [comment]
I can write that in, and commit it within the next few days. @rawsonj , can you assign this ticket to me?

**Comment by andy5995** [comment]
@rawsonj I can apply this patch once it's reviewed and approved.
```
@@ -213,7 +218,9 @@ class triviabot(irc.IRCClient):
             self.msg(channel,
                      "I'm sorry, answers must be given in the game channel.")
             return
-        self._gmsg("%s GOT IT!" % user.upper())
+        self._gmsg("%s GOT IT!\n" % user.upper())
+        self._gmsg("If there was any doubt, the correct answer was:\n")
+        self._gmsg("%s\n" % self._answer.answer)
         try:
             self._scores[user] += self._current_points
         except:
```

**Comment by rawsonj** [comment]
lol, I like the message. We should play test it a bit.

**Comment by andy5995** [comment]
:) Sure, it's already included in the bot running in #triviabot-dev and #triviabot

Hey, @rawsonj, by the way, thanks for the github invite and adding me as a contributor.

**Comment by andy5995** [comment]
@rawsonj Does that patch need tweaking at all? From our discussion on IRC, I got the impression you were okay with it as is, but I wasn't sure if needed any tweaking.

I'll run the diff against your new code though before I try applying it. I haven't had time to study all your new changes yet.

**Comment by rawsonj** [comment]
I'm ok with the patch you have to close this issue out.

Go ahead and merge it and close the issue.

**Comment by andy5995** [comment]
Done.
