### ISSUE TITLE
Daemonize the bot and make a debug mode.

### ISSUE THREAD

**Issue by rawsonj** [rawsonj/triviabot#29]
I'm tired of running it in a screen. We don't have to stay attached to the thing while its running, and it makes sense to daemonise it unless we pass it a --debug, where it will not daemonise and will interact with whoever is attached to it.

**Comment by rawsonj** [comment]
http://web.archive.org/web/20131017130434/http://www.jejik.com/articles/2007/02/a_simple_unix_linux_daemon_in_python/

Shows a python daemon implementation.

Alternatively, we could just write a bash wrapper that does the needful, but I'm less inclined to do that than  something in python I think.

**Comment by andy5995** [comment]
I'd say that if it can be done in python, then there's no real reason to have a separate BASH script.

With one exception: my initial thoughts are that a BASH script could still be included to give the user the option to integrate it into their init scripts. But the primary daemonization would be coded into the .py file.

And for the record, I'm much better with BASH than python, atm. ;) That's something I'd be able to work on.

**Comment by rawsonj** [comment]
I'm just weighing the relative complexity of incorporating the above linked daemon code vs. just writing a bash wrapper that goes `nohup python trivia.py &`

The latter is a lot less code and very easy to maintain. The former... well I'm not sure yet. I think it depends on how much time either of us want to put into it.

**Comment by andy5995** [comment]
I'm leaning toward option 1.

If there's some reason more complex needs to be added in the future, or until users start giving us reason why a native daemon method would be better, I think the bash wrapper is the way to go.

**Comment by rawsonj** [comment]
Ok. I'll add something.
