### ISSUE TITLE
AARGH IT WON'T PARSE NEGATIVE ANSWERS

### ISSUE THREAD

**Issue by edunham** [rawsonj/triviabot#39]
sorry, but it just stole some points.

21:17 <@trivia> Question:
21:17 <@trivia> At what temperature do Fahrenheit & Celcius give the same 
                value
21:17 <@trivia> Clue: -40
21:17 < edunham> -40

aaand... no win.

**Comment by edunham** [comment]
Thanks for the fix!

**Comment by rawsonj** [comment]
Sure thing. It only took 2 years and a bit of prodding me to fix it. ;)
