### ISSUE TITLE
Official #triviabot-dev channel on QuakeNet

### ISSUE THREAD

**Issue by andy5995** [rawsonj/triviabot#54]
I registered an unofficial #triviabot-dev channel on Quakenet.

If @rawsonj wants to make it official, please let me know and I will op you and grant you ownership privileges.

If you'd like it deleted because of any conflicts with existing channels, I can do that too. :)

As far as I know, there's no existing dev IRC channel for triviabot. Is that right?

**Comment by rawsonj** [comment]
Not really. Most people have just pinged me on irc.cat.pdx.edu or freenode before, since this has been a lonely little project with no one really contributing to it.

**Comment by andy5995** [comment]
The channel seems to be "official" now. ;)

**Comment by rawsonj** [comment]
As official as anything on a casual project. :)

**Comment by andy5995** [comment]
I was harmlessly testing some bots, but apparently there is a 5 connection limit on QuakeNet. I've been banned either temporarily or permanently.
https://www.quakenet.org/help/trusts/connection-limit

**Comment by andy5995** [comment]
It was temporary.
