### ISSUE TITLE
clues give away answers that are 3 characters or less

### ISSUE THREAD

**Issue by andy5995** [rawsonj/triviabot#55]
Clues give away answers that are 3 characters or less.

Some answers are only one letter, and it's shown after the first hint.

And years can be pretty easy to guess, too.

_691

Hmm.. probably 1. ;)

Maybe only give 1 clue if string length is less than 3, and no clues on answers that are only 1 character? Something along those lines?

**Comment by rawsonj** [comment]
I always thought of these as "speed round" or gimmie questions.

If you're playing with a group of people, it turns into who can get to the answer the fastest, which can be fun.

That said, I'm not opposed to implementing the changes you have proposed here. I think it could be fun either way.

**Comment by andy5995** [comment]
I definitely lean toward adjusting that function.

I see many questions that are relatively easy, so I think there would still be an element of who can get the answer the fastest in a group of people.

I wouldn't mind hearing from other people on this. Anyone else have opinions? ;)

It's code that I'm reasonably certain I could write, once it's decided on how it would work.

The questions could still be asked 3 times, which gives players time to guess and answer.

2 character words get no clues. The question would get repeated but no extra clues show.

3 - 4 chars get 1 clue.

5 - 6 get 2 clues.

7 and over get the usual 3 clues.

Unless you have other thoughts on how it would function? Let me know...

**Comment by rawsonj** [comment]
I think this could be entirely done in the Answer class in lib/answer.py.

And I think the proposed changes here are fine. Go ahead and make a pull request and I'll review.

**Comment by andy5995** [comment]
[55_patch.1.txt](https://github.com/rawsonj/triviabot/files/450400/55_patch.1.txt)

Initially, I couldn't figure out how to do this in the Answer class, but after spending 3 hours on it, I think I could that now. ;)

Anyway, do you have suggestions for tightening this up? I tested it, and it works as is. I'll activate it in #triviabot-dev

**Comment by andy5995** [comment]
Hmm.. the 2 commits that I removed are still showing here, and apparently I can't delete them from this thread.

Sorry for any confusion. The changes presently showing on the issue55 branch are the same as in patch.2, attached above.

**Comment by rawsonj** [comment]
You generally can't remove history, and rewriting history will break other people's repos.

What would make this easier for me to review would be if you created a branch, committed those changes to the branch and then pushed the branch to the repo using `git push origin <branch-name>`.

That way I can pull the branch and use `git diff` to review instead of downloading files and opening them.

**Comment by andy5995** [comment]
Ok, that's how I'll do it from now on. I read up on branches yesterday, and by now you've seen the branch I created.
