### ISSUE TITLE
HI

### ISSUE THREAD

**Issue by JesuTinto** [rawsonj/triviabot#76]
### **

- 1. Hello greetings. I was wondering, if anyone can answer my question. I am not a python coder, nor a programmer. But the bot is very good. I've been running it, and is very amazing. The only request. I am asking. if someone can help me to. achieved this. for example when every time a. User answers the correct answer. it says nick got it.
- 2. what. I want to achieved is for example to say nick you got it. and then to stay all the scores from the users. who are in the database. Of the bot. and also can you guys port the bot to python3? thank you in advance.

**

**Comment by rawsonj** [comment]
1. It wouldn't be hard to say "nick, you got it!"
2. There is no way I'm going to have the bot say all the scores in the DB.
I'm currently running a bot that has several hundred users in the DB. There
is no way the bot would be playable in that case.
3. I can port it to python3.
